### PR TITLE
Update play service

### PR DESCRIPTION
**Pull request by hannesa2**
* update Google play service to most recent
* update Gradle tools version
With this commit, developer are no more forced to change AME when we use it as git submodule and want update libraries

### CODE REVIEW

**Comment by mg6maciej** [comment]
Thanks. I've changed names of properties to more unique in case someone has such defined and to more natural in case someone wants to set them via env vars.

**Comment by hannesa2** [comment]
I agree about any names, but moving it to top build.gradle file (and not in module) doesn't work for me when I use it as submodule 
```
include ':android-maps-extensions:android-maps-extensions'
```
```
dependencies {
    compile project(':android-maps-extensions:android-maps-extensions')
```

> Error:(12, 0) Could not get unknown property 'localCompileSdkVersion' for object of type com.android.build.gradle.LibraryExtension.

I know, on the other side, have it twice, is not beautiful, but works

**Comment by mg6maciej** [comment]
So you probably don't need it defined in demo, right? These should be separate repos anyway.

**Comment by hannesa2** [comment]
correct, I don't need it on demo. but found a workaround, in my build.gradle I do 
```
ext {
    localCompileSdkVersion = 25
    localMinSdkVersion = 14
    localBuildToolsVersion = "25.0.2"
    playServicesVersion = "10.2.4"
```
and ignoring all your AME_xxx variables. In my point of view, all AME_xxx variables are just for the demo...

**Comment by hannesa2** [comment]
Ahh, I see you already changed it. Thank you !

**Pull request merged**
