### PR TITLE
Added support for Marker zIndex

### PR DESCRIPTION
**Pull request by hannta**
Added support for Marker zIndex, introduced in Google play services maps 9.2.0.

**Breaking changes**
- Removed getExtendedMap() as getMap() is not any more available in Google play services sdk
- minSdkVersion is now 9

### CODE REVIEW

**Comment by mg6maciej** [comment]
Hello Hannu.
Thanks for PR. I'm on longer vacations now, so I'll handle this in a few months.
I just skimmed through the changes. Can you make `ClusterMarker::getZIndex` to also throw exception?
I'll also have to think, how to handle dissapearance of `getMap` method better than also removing it from AME. Someone could still want to use it with older version of Google Maps SDK. Reflection comes to my mind.
Also don't worry about Travis. I'll fix that too after vacations.
Cheers,
Maciej

**Comment by hannta** [comment]
Hi Maciej,

I changed the ClusterMarker getZIndex to throw unsupported exception.

There is definitely some room for improvements in getMap handling, to keep AME backward compatibly. 

Have a nice vacation! :)

**Comment by mg6maciej** [comment]
I have merged your changes and now updating AME to contain other things recently added to Google Maps Android API v2. Will release it to maven central / jcenter soon. Thanks.

**Comment by hannta** [comment]
Thanks! Google has been quite active on adding new features to Google maps for android recently.

**Comment by mg6maciej** [comment]
This is now fixed in version 2.3.0. I have also added delegation for all features added recently in Google Maps Android API. Let me know if I missed something.

**Comment by Tushar-Salvi** [comment]
Hi @mg6maciej 
When i upgrated to latest version, i get runtime error on my inflate layout in fragment

my layout code is 

<LinearLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical"
        tools:visibility="visible">

```
    <fragment
        android:id="@+id/map"
        android:name="com.androidmapsextensions.SupportMapFragment"
        class="com.androidmapsextensions.SupportMapFragment"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:visibility="visible" />
</LinearLayout>
```

and error what i get in log is 

java.lang.VerifyError: com/google/android/gms/maps/SupportMapFragment
                                                                            at java.lang.Class.newInstanceImpl(Native Method)
                                                                            at java.lang.Class.newInstance(Class.java:1208)
                                                                            at android.support.v4.app.Fragment.instantiate(Fragment.java:432)
                                                                            at android.support.v4.app.Fragment.instantiate(Fragment.java:407)
                                                                            at android.support.v4.app.FragmentManagerImpl.onCreateView(FragmentManager.java:2406)
                                                                            at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:44)
                                                                            at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:169)
                                                                            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:684)
                                                                            at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
                                                                            at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
                                                                            at android.view.LayoutInflater.parseInclude(LayoutInflater.java:839)
                                                                            at android.view.LayoutInflater.rInflate(LayoutInflater.java:745)
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
                                                                            at android.support.v4.app.Fragment.performCreateView(Fragment.java:2080)
                                                                            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1108)
                                                                            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1290)
                                                                            at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:801)
                                                                            at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1677)
                                                                            at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:388)
                                                                            at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:604)
                                                                            at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
                                                                            at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1171)
                                                                            at android.app.Activity.performStart(Activity.java:5241)
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2157)
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233)
                                                                            at android.app.ActivityThread.access$800(ActivityThread.java:135)
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                            at android.os.Looper.loop(Looper.java:136)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5001)
                                                                            at java.lang.reflect.Method.invokeNative(Native Method)
                                                                            at java.lang.reflect.Method.invoke(Method.java:515)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                                            at dalvik.system.NativeStart.main(Native Method)

**Comment by Tushar-Salvi** [comment]
and map declaration in this way

 GoogleMap mGoogleMap = ((SupportMapFragment) getChildFragmentManager().findFragmentById(R.id.map)).getExtendedMap();

**Comment by mg6maciej** [comment]
Hey Tushar,
Did your code work with previous versions of AME and Google Maps API?
I just tested it by adding a fragment inside `Activity`'s xml and it worked (showed a map).
I have no idea why you would get a `VerifyError`, but nested fragments are not supported via xml. Unless something changed recently, they need to be added via code. Take a look here: https://developer.android.com/about/versions/android-4.2.html#NestedFragments

**Comment by Tushar-Salvi** [comment]
Hi Maciej,

When I update your library and used Google play services with latest
version I.e 9.6.1 that time I get that error. But when I used Google play
service version 8.4.0 it works.

**Comment by Tushar-Salvi** [comment]
Hi @mg6maciej 

Can you help me with the sample app which you have tried by adding fragment.

**Comment by mg6maciej** [comment]
The demo applicaton contains [code to add `SupportMapFragment` dynamically to another `Fragment`](https://github.com/mg6maciej/android-maps-extensions/blob/develop/android-maps-extensions-demo/src/main/java/pl/mg6/android/maps/extensions/demo/BaseFragment.java). Like I mentioned before, adding `Fragment` inside another `Fragment` should not be done via XML. If you still have problems and think AME or Google Maps API cause the issue, please create a short, compilable example that exposes it, so I may look into it.

**Comment by Tushar-Salvi** [comment]
Hi Maciej,

I have made a demo example for map using AME library. In this demo i have
used
compile 'com.google.android.gms:play-services-maps:8.4.0'
compile 'com.androidmapsextensions:android-maps-extensions:2.3.0'
but when i used latest library for google play service i.e
​compile 'com.google.android.gms:play-services-maps:9.6.1'
it throw error. Only 2 thing you have to change in demo i.e google api key,
and google play service library version.
If i made any mistake please correct me.

​
 AMEDemo.rar
<https://drive.google.com/file/d/0BzCk4PLcUmgLUmZWY2lscG5meDA/view?usp=drive_web>
​
​​




*Thanks and Regards,*
Tushar Salvi.
Software Developer(Android)

**Comment by mg6maciej** [comment]
@Tushar-Salvi  When using Google Maps Android API 9.2 or newer you cannot use `getExtendedMap` method, because it uses `getMap` underneath. Use `getExtendedMapAsync` instead.

**Comment by Tushar-Salvi** [comment]
Hi @mg6maciej 

i used getExtendedMapAsync() it's working great now. Thanks for your help.

**Comment by maxime-kouemo** [comment]
Thank you so much for this library

**Pull request merged**
